- name: kind/bug
  color: d73a4a
  description: Categorizes issue or PR as related to a bug.
- name: kind/feature
  color: a2eeef
  description: Categorizes issue or PR as related to a new feature.
- name: kind/documentation
  color: 0075ca
  description: Categorizes issue or PR as related to documentation.
- name: kind/test
  color: ddc23b
  description: Categorizes issue or PR as related to tests.
- name: kind/cleanup
  color: ededed
  description: Categorizes issue or PR as related to cleaning up code, process, or
    technical debt.
- name: kind/dependencies
  color: ededed
  description: Pull requests that update a dependency file
- name: kind/security
  color: 10cc8a
  description: Categorizes issue or PR as related to security.
- name: kind/question
  color: 775FCB
  description: Categorizes issues related to questions.
- name: lifecycle/stale
  color: 795548
  description: Denotes an issue or PR has remained open with no activity and has become
    stale.
- name: lifecycle/frozen
  color: d3e2f0
  description: Indicates that an issue or PR should not be auto-closed due to staleness.
- name: size/XS
  color: 009900
  description: Denotes a PR that changes 0-9 lines, ignoring generated files.
- name: size/S
  color: 77bb00
  description: Denotes a PR that changes 10-29 lines, ignoring generated files.
- name: size/M
  color: eebb00
  description: Denotes a PR that changes 30-99 lines, ignoring generated files.
- name: size/L
  color: ee9900
  description: Denotes a PR that changes 100-499 lines, ignoring generated files.
- name: size/XL
  color: ee5500
  description: Denotes a PR that changes 500-999 lines, ignoring generated files.
- name: size/XXL
  color: ee0000
  description: Denotes a PR that changes 1000+ lines, ignoring generated files.
- name: help wanted
  color: 008672
  description: Denotes an issue that needs help from a contributor.
- name: good first issue
  color: 7057ff
  description: Denotes an issue ready for a new contributor.
- name: hold
  color: e11d21
  description: Indicates that a PR should not merge.
- name: work-in-progress
  color: e01dd6
  description: Indicates that a PR is still in progress.
