name: code-checks

on:
  pull_request: {}
  push:
    branches:
      - "**"

jobs:
  gosec:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.19.1'

      - name: Checkout
        uses: actions/checkout@v3

      - name: Gosec Security Scanner
        run: |
          make bootstrap-tools
          make lintsec

  golint:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.19.1'

      - name: Checkout
        uses: actions/checkout@v3

      - name: Golint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.48.0
          args: --timeout 5m
